import type { ConsentDescription } from '@cloudflare/workers-oauth-provider';
export const escapeHtml = (s: string) => s.replace(/[&<>"']/g, c => `&#${c.charCodeAt(0)};`);
export function page(title: string, body: string) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><style>body{font:17px/1.6 system-ui,sans-serif;background:#f4f3ef;color:#242b28;margin:0;padding:12vh 24px}main{max-width:660px;margin:auto}small{letter-spacing:.13em;text-transform:uppercase;color:#57665f}h1{font-size:clamp(36px,7vw,56px);line-height:1.1;font-weight:600}p{color:#49554e}code{overflow-wrap:anywhere;background:#e4e8e1;padding:4px 7px;border-radius:5px}section{margin:32px 0;padding:24px;border:1px solid #ccd3c8;border-radius:14px;background:#fff}button{font:inherit;padding:10px 18px;border:1px solid #254f3d;border-radius:7px;background:#254f3d;color:#fff;cursor:pointer;margin:8px 8px 0 0}button[value=deny]{background:white;color:#254f3d}a{color:#254f3d}li{margin:8px 0}</style></head><body><main><small>Personal vault</small><h1>${escapeHtml(title)}</h1>${body}</main></body></html>`;
}
export function home(origin: string) {
  return page('Your notes. Always available.', `<p>A private notebook for ChatGPT and other MCP clients, hosted on Cloudflare.</p><section><h2>Connect your client</h2><p>MCP endpoint:</p><p><code>${escapeHtml(origin)}/mcp</code></p><p>Choose OAuth authentication in your MCP client. GitHub sign-in authorizes access to the vault.</p></section><p>This public page contains no notes or private vault status. No laptop service or open browser tab is required.</p>`);
}
export function consentPage(d: ConsentDescription, handle: string) {
  return page('Connect your vault?', `<p><strong>${escapeHtml(d.clientName)}</strong> requests permission to read, search, and create notes. It cannot overwrite or delete notes.</p><p>${d.clientDomain ? `Client domain: <strong>${escapeHtml(d.clientDomain)}</strong>` : 'The client name is self-reported and not verified.'}</p><p>Access will be returned to <strong>${escapeHtml(d.redirectHost)}</strong>.</p>${d.redirectIsLoopback ? '<p>This authorizes an app on your computer. Continue only if you started this connection.</p>' : ''}<p>Only the vault owner can approve access using GitHub.</p><form method="post" action="/authorize"><input type="hidden" name="handle" value="${escapeHtml(handle)}"><button name="decision" value="approve">Continue with GitHub</button><button name="decision" value="deny">Cancel</button></form>`);
}
